#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSanBongGit.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DATA_WEB_QUAN_LY_SAN_BONG")]
	public partial class DATA_SAN_BONGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertCHUC_VU_ADM(CHUC_VU_ADM instance);
    partial void UpdateCHUC_VU_ADM(CHUC_VU_ADM instance);
    partial void DeleteCHUC_VU_ADM(CHUC_VU_ADM instance);
    partial void InsertCT_DAT_SAN(CT_DAT_SAN instance);
    partial void UpdateCT_DAT_SAN(CT_DAT_SAN instance);
    partial void DeleteCT_DAT_SAN(CT_DAT_SAN instance);
    partial void InsertDON_DAT_SAN(DON_DAT_SAN instance);
    partial void UpdateDON_DAT_SAN(DON_DAT_SAN instance);
    partial void DeleteDON_DAT_SAN(DON_DAT_SAN instance);
    partial void InsertKHACH_HANG(KHACH_HANG instance);
    partial void UpdateKHACH_HANG(KHACH_HANG instance);
    partial void DeleteKHACH_HANG(KHACH_HANG instance);
    partial void InsertLOAI_SAN(LOAI_SAN instance);
    partial void UpdateLOAI_SAN(LOAI_SAN instance);
    partial void DeleteLOAI_SAN(LOAI_SAN instance);
    partial void InsertSAN(SAN instance);
    partial void UpdateSAN(SAN instance);
    partial void DeleteSAN(SAN instance);
    partial void InsertSO_GIO(SO_GIO instance);
    partial void UpdateSO_GIO(SO_GIO instance);
    partial void DeleteSO_GIO(SO_GIO instance);
    partial void InsertTHONG_KE(THONG_KE instance);
    partial void UpdateTHONG_KE(THONG_KE instance);
    partial void DeleteTHONG_KE(THONG_KE instance);
    partial void InsertSO_PHUT(SO_PHUT instance);
    partial void UpdateSO_PHUT(SO_PHUT instance);
    partial void DeleteSO_PHUT(SO_PHUT instance);
    #endregion
		
		public DATA_SAN_BONGDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DATA_WEB_QUAN_LY_SAN_BONGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DATA_SAN_BONGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATA_SAN_BONGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATA_SAN_BONGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATA_SAN_BONGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<CHUC_VU_ADM> CHUC_VU_ADMs
		{
			get
			{
				return this.GetTable<CHUC_VU_ADM>();
			}
		}
		
		public System.Data.Linq.Table<CT_DAT_SAN> CT_DAT_SANs
		{
			get
			{
				return this.GetTable<CT_DAT_SAN>();
			}
		}
		
		public System.Data.Linq.Table<DON_DAT_SAN> DON_DAT_SANs
		{
			get
			{
				return this.GetTable<DON_DAT_SAN>();
			}
		}
		
		public System.Data.Linq.Table<KHACH_HANG> KHACH_HANGs
		{
			get
			{
				return this.GetTable<KHACH_HANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_SAN> LOAI_SANs
		{
			get
			{
				return this.GetTable<LOAI_SAN>();
			}
		}
		
		public System.Data.Linq.Table<SAN> SANs
		{
			get
			{
				return this.GetTable<SAN>();
			}
		}
		
		public System.Data.Linq.Table<SO_GIO> SO_GIOs
		{
			get
			{
				return this.GetTable<SO_GIO>();
			}
		}
		
		public System.Data.Linq.Table<THONG_KE> THONG_KEs
		{
			get
			{
				return this.GetTable<THONG_KE>();
			}
		}
		
		public System.Data.Linq.Table<SO_PHUT> SO_PHUTs
		{
			get
			{
				return this.GetTable<SO_PHUT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TEN_DANG_NHAP_ADM;
		
		private string _MAT_KHAU_ADM;
		
		private int _STT;
		
		private System.Nullable<int> _MA_CHUC_VU;
		
		private EntityRef<CHUC_VU_ADM> _CHUC_VU_ADM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTEN_DANG_NHAP_ADMChanging(string value);
    partial void OnTEN_DANG_NHAP_ADMChanged();
    partial void OnMAT_KHAU_ADMChanging(string value);
    partial void OnMAT_KHAU_ADMChanged();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMA_CHUC_VUChanging(System.Nullable<int> value);
    partial void OnMA_CHUC_VUChanged();
    #endregion
		
		public ADMIN()
		{
			this._CHUC_VU_ADM = default(EntityRef<CHUC_VU_ADM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DANG_NHAP_ADM", DbType="NVarChar(50)")]
		public string TEN_DANG_NHAP_ADM
		{
			get
			{
				return this._TEN_DANG_NHAP_ADM;
			}
			set
			{
				if ((this._TEN_DANG_NHAP_ADM != value))
				{
					this.OnTEN_DANG_NHAP_ADMChanging(value);
					this.SendPropertyChanging();
					this._TEN_DANG_NHAP_ADM = value;
					this.SendPropertyChanged("TEN_DANG_NHAP_ADM");
					this.OnTEN_DANG_NHAP_ADMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT_KHAU_ADM", DbType="NVarChar(50)")]
		public string MAT_KHAU_ADM
		{
			get
			{
				return this._MAT_KHAU_ADM;
			}
			set
			{
				if ((this._MAT_KHAU_ADM != value))
				{
					this.OnMAT_KHAU_ADMChanging(value);
					this.SendPropertyChanging();
					this._MAT_KHAU_ADM = value;
					this.SendPropertyChanged("MAT_KHAU_ADM");
					this.OnMAT_KHAU_ADMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CHUC_VU", DbType="Int")]
		public System.Nullable<int> MA_CHUC_VU
		{
			get
			{
				return this._MA_CHUC_VU;
			}
			set
			{
				if ((this._MA_CHUC_VU != value))
				{
					if (this._CHUC_VU_ADM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_CHUC_VUChanging(value);
					this.SendPropertyChanging();
					this._MA_CHUC_VU = value;
					this.SendPropertyChanged("MA_CHUC_VU");
					this.OnMA_CHUC_VUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUC_VU_ADM_ADMIN", Storage="_CHUC_VU_ADM", ThisKey="MA_CHUC_VU", OtherKey="MA_CHUC_VU", IsForeignKey=true)]
		public CHUC_VU_ADM CHUC_VU_ADM
		{
			get
			{
				return this._CHUC_VU_ADM.Entity;
			}
			set
			{
				CHUC_VU_ADM previousValue = this._CHUC_VU_ADM.Entity;
				if (((previousValue != value) 
							|| (this._CHUC_VU_ADM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUC_VU_ADM.Entity = null;
						previousValue.ADMINs.Remove(this);
					}
					this._CHUC_VU_ADM.Entity = value;
					if ((value != null))
					{
						value.ADMINs.Add(this);
						this._MA_CHUC_VU = value.MA_CHUC_VU;
					}
					else
					{
						this._MA_CHUC_VU = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHUC_VU_ADM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUC_VU_ADM")]
	public partial class CHUC_VU_ADM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_CHUC_VU;
		
		private string _TEN_CHUC_VU;
		
		private EntitySet<ADMIN> _ADMINs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_CHUC_VUChanging(int value);
    partial void OnMA_CHUC_VUChanged();
    partial void OnTEN_CHUC_VUChanging(string value);
    partial void OnTEN_CHUC_VUChanged();
    #endregion
		
		public CHUC_VU_ADM()
		{
			this._ADMINs = new EntitySet<ADMIN>(new Action<ADMIN>(this.attach_ADMINs), new Action<ADMIN>(this.detach_ADMINs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CHUC_VU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_CHUC_VU
		{
			get
			{
				return this._MA_CHUC_VU;
			}
			set
			{
				if ((this._MA_CHUC_VU != value))
				{
					this.OnMA_CHUC_VUChanging(value);
					this.SendPropertyChanging();
					this._MA_CHUC_VU = value;
					this.SendPropertyChanged("MA_CHUC_VU");
					this.OnMA_CHUC_VUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_CHUC_VU", DbType="NVarChar(32)")]
		public string TEN_CHUC_VU
		{
			get
			{
				return this._TEN_CHUC_VU;
			}
			set
			{
				if ((this._TEN_CHUC_VU != value))
				{
					this.OnTEN_CHUC_VUChanging(value);
					this.SendPropertyChanging();
					this._TEN_CHUC_VU = value;
					this.SendPropertyChanged("TEN_CHUC_VU");
					this.OnTEN_CHUC_VUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUC_VU_ADM_ADMIN", Storage="_ADMINs", ThisKey="MA_CHUC_VU", OtherKey="MA_CHUC_VU")]
		public EntitySet<ADMIN> ADMINs
		{
			get
			{
				return this._ADMINs;
			}
			set
			{
				this._ADMINs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ADMINs(ADMIN entity)
		{
			this.SendPropertyChanging();
			entity.CHUC_VU_ADM = this;
		}
		
		private void detach_ADMINs(ADMIN entity)
		{
			this.SendPropertyChanging();
			entity.CHUC_VU_ADM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_DAT_SAN")]
	public partial class CT_DAT_SAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_DS;
		
		private int _MA_SAN;
		
		private System.Nullable<System.DateTime> _NGAY_DAT;
		
		private System.Nullable<decimal> _TONG_TIEN;
		
		private System.Nullable<bool> _TINH_TRANG_THANH_TOAN;
		
		private EntityRef<DON_DAT_SAN> _DON_DAT_SAN;
		
		private EntityRef<SAN> _SAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DSChanging(int value);
    partial void OnMA_DSChanged();
    partial void OnMA_SANChanging(int value);
    partial void OnMA_SANChanged();
    partial void OnNGAY_DATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_DATChanged();
    partial void OnTONG_TIENChanging(System.Nullable<decimal> value);
    partial void OnTONG_TIENChanged();
    partial void OnTINH_TRANG_THANH_TOANChanging(System.Nullable<bool> value);
    partial void OnTINH_TRANG_THANH_TOANChanged();
    #endregion
		
		public CT_DAT_SAN()
		{
			this._DON_DAT_SAN = default(EntityRef<DON_DAT_SAN>);
			this._SAN = default(EntityRef<SAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_DS
		{
			get
			{
				return this._MA_DS;
			}
			set
			{
				if ((this._MA_DS != value))
				{
					if (this._DON_DAT_SAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_DSChanging(value);
					this.SendPropertyChanging();
					this._MA_DS = value;
					this.SendPropertyChanged("MA_DS");
					this.OnMA_DSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SAN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_SAN
		{
			get
			{
				return this._MA_SAN;
			}
			set
			{
				if ((this._MA_SAN != value))
				{
					if (this._SAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SANChanging(value);
					this.SendPropertyChanging();
					this._MA_SAN = value;
					this.SendPropertyChanged("MA_SAN");
					this.OnMA_SANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_DAT
		{
			get
			{
				return this._NGAY_DAT;
			}
			set
			{
				if ((this._NGAY_DAT != value))
				{
					this.OnNGAY_DATChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DAT = value;
					this.SendPropertyChanged("NGAY_DAT");
					this.OnNGAY_DATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONG_TIEN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TONG_TIEN
		{
			get
			{
				return this._TONG_TIEN;
			}
			set
			{
				if ((this._TONG_TIEN != value))
				{
					this.OnTONG_TIENChanging(value);
					this.SendPropertyChanging();
					this._TONG_TIEN = value;
					this.SendPropertyChanged("TONG_TIEN");
					this.OnTONG_TIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH_TRANG_THANH_TOAN", DbType="Bit")]
		public System.Nullable<bool> TINH_TRANG_THANH_TOAN
		{
			get
			{
				return this._TINH_TRANG_THANH_TOAN;
			}
			set
			{
				if ((this._TINH_TRANG_THANH_TOAN != value))
				{
					this.OnTINH_TRANG_THANH_TOANChanging(value);
					this.SendPropertyChanging();
					this._TINH_TRANG_THANH_TOAN = value;
					this.SendPropertyChanged("TINH_TRANG_THANH_TOAN");
					this.OnTINH_TRANG_THANH_TOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DON_DAT_SAN_CT_DAT_SAN", Storage="_DON_DAT_SAN", ThisKey="MA_DS", OtherKey="MA_DS", IsForeignKey=true)]
		public DON_DAT_SAN DON_DAT_SAN
		{
			get
			{
				return this._DON_DAT_SAN.Entity;
			}
			set
			{
				DON_DAT_SAN previousValue = this._DON_DAT_SAN.Entity;
				if (((previousValue != value) 
							|| (this._DON_DAT_SAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DON_DAT_SAN.Entity = null;
						previousValue.CT_DAT_SANs.Remove(this);
					}
					this._DON_DAT_SAN.Entity = value;
					if ((value != null))
					{
						value.CT_DAT_SANs.Add(this);
						this._MA_DS = value.MA_DS;
					}
					else
					{
						this._MA_DS = default(int);
					}
					this.SendPropertyChanged("DON_DAT_SAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_CT_DAT_SAN", Storage="_SAN", ThisKey="MA_SAN", OtherKey="MA_SAN", IsForeignKey=true)]
		public SAN SAN
		{
			get
			{
				return this._SAN.Entity;
			}
			set
			{
				SAN previousValue = this._SAN.Entity;
				if (((previousValue != value) 
							|| (this._SAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN.Entity = null;
						previousValue.CT_DAT_SANs.Remove(this);
					}
					this._SAN.Entity = value;
					if ((value != null))
					{
						value.CT_DAT_SANs.Add(this);
						this._MA_SAN = value.MA_SAN;
					}
					else
					{
						this._MA_SAN = default(int);
					}
					this.SendPropertyChanged("SAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DON_DAT_SAN")]
	public partial class DON_DAT_SAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_DS;
		
		private System.Nullable<int> _MA_KH;
		
		private System.Nullable<System.DateTime> _NGAY_DAT;
		
		private System.Nullable<System.DateTime> _GIO_BAT_DAU;
		
		private System.Nullable<System.DateTime> _GIO_KET_THUC;
		
		private int _MA_SAN;
		
		private System.Nullable<decimal> _TONG_TIEN;
		
		private string _TONG_GIO_THUE;
		
		private System.Nullable<decimal> _GIA_SAN;
		
		private System.Nullable<System.DateTime> _NGAY_LAP_PHIEU;
		
		private System.Nullable<bool> _TINH_TRANG_DON;
		
		private string _GIO_KET_THUC_TEXT;
		
		private System.Nullable<bool> _TRANG_THAI_XOA;
		
		private System.Nullable<int> _TIME_START;
		
		private System.Nullable<int> _TIME_END;
		
		private EntitySet<CT_DAT_SAN> _CT_DAT_SANs;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
		private EntityRef<SAN> _SAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DSChanging(int value);
    partial void OnMA_DSChanged();
    partial void OnMA_KHChanging(System.Nullable<int> value);
    partial void OnMA_KHChanged();
    partial void OnNGAY_DATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_DATChanged();
    partial void OnGIO_BAT_DAUChanging(System.Nullable<System.DateTime> value);
    partial void OnGIO_BAT_DAUChanged();
    partial void OnGIO_KET_THUCChanging(System.Nullable<System.DateTime> value);
    partial void OnGIO_KET_THUCChanged();
    partial void OnMA_SANChanging(int value);
    partial void OnMA_SANChanged();
    partial void OnTONG_TIENChanging(System.Nullable<decimal> value);
    partial void OnTONG_TIENChanged();
    partial void OnTONG_GIO_THUEChanging(string value);
    partial void OnTONG_GIO_THUEChanged();
    partial void OnGIA_SANChanging(System.Nullable<decimal> value);
    partial void OnGIA_SANChanged();
    partial void OnNGAY_LAP_PHIEUChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_LAP_PHIEUChanged();
    partial void OnTINH_TRANG_DONChanging(System.Nullable<bool> value);
    partial void OnTINH_TRANG_DONChanged();
    partial void OnGIO_KET_THUC_TEXTChanging(string value);
    partial void OnGIO_KET_THUC_TEXTChanged();
    partial void OnTRANG_THAI_XOAChanging(System.Nullable<bool> value);
    partial void OnTRANG_THAI_XOAChanged();
    partial void OnTIME_STARTChanging(System.Nullable<int> value);
    partial void OnTIME_STARTChanged();
    partial void OnTIME_ENDChanging(System.Nullable<int> value);
    partial void OnTIME_ENDChanged();
    #endregion
		
		public DON_DAT_SAN()
		{
			this._CT_DAT_SANs = new EntitySet<CT_DAT_SAN>(new Action<CT_DAT_SAN>(this.attach_CT_DAT_SANs), new Action<CT_DAT_SAN>(this.detach_CT_DAT_SANs));
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			this._SAN = default(EntityRef<SAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_DS
		{
			get
			{
				return this._MA_DS;
			}
			set
			{
				if ((this._MA_DS != value))
				{
					this.OnMA_DSChanging(value);
					this.SendPropertyChanging();
					this._MA_DS = value;
					this.SendPropertyChanged("MA_DS");
					this.OnMA_DSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", DbType="Int")]
		public System.Nullable<int> MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_DAT
		{
			get
			{
				return this._NGAY_DAT;
			}
			set
			{
				if ((this._NGAY_DAT != value))
				{
					this.OnNGAY_DATChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DAT = value;
					this.SendPropertyChanged("NGAY_DAT");
					this.OnNGAY_DATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIO_BAT_DAU", DbType="DateTime")]
		public System.Nullable<System.DateTime> GIO_BAT_DAU
		{
			get
			{
				return this._GIO_BAT_DAU;
			}
			set
			{
				if ((this._GIO_BAT_DAU != value))
				{
					this.OnGIO_BAT_DAUChanging(value);
					this.SendPropertyChanging();
					this._GIO_BAT_DAU = value;
					this.SendPropertyChanged("GIO_BAT_DAU");
					this.OnGIO_BAT_DAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIO_KET_THUC", DbType="DateTime")]
		public System.Nullable<System.DateTime> GIO_KET_THUC
		{
			get
			{
				return this._GIO_KET_THUC;
			}
			set
			{
				if ((this._GIO_KET_THUC != value))
				{
					this.OnGIO_KET_THUCChanging(value);
					this.SendPropertyChanging();
					this._GIO_KET_THUC = value;
					this.SendPropertyChanged("GIO_KET_THUC");
					this.OnGIO_KET_THUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SAN", DbType="Int NOT NULL")]
		public int MA_SAN
		{
			get
			{
				return this._MA_SAN;
			}
			set
			{
				if ((this._MA_SAN != value))
				{
					if (this._SAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SANChanging(value);
					this.SendPropertyChanging();
					this._MA_SAN = value;
					this.SendPropertyChanged("MA_SAN");
					this.OnMA_SANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONG_TIEN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TONG_TIEN
		{
			get
			{
				return this._TONG_TIEN;
			}
			set
			{
				if ((this._TONG_TIEN != value))
				{
					this.OnTONG_TIENChanging(value);
					this.SendPropertyChanging();
					this._TONG_TIEN = value;
					this.SendPropertyChanged("TONG_TIEN");
					this.OnTONG_TIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONG_GIO_THUE", DbType="NVarChar(6)")]
		public string TONG_GIO_THUE
		{
			get
			{
				return this._TONG_GIO_THUE;
			}
			set
			{
				if ((this._TONG_GIO_THUE != value))
				{
					this.OnTONG_GIO_THUEChanging(value);
					this.SendPropertyChanging();
					this._TONG_GIO_THUE = value;
					this.SendPropertyChanged("TONG_GIO_THUE");
					this.OnTONG_GIO_THUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_SAN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIA_SAN
		{
			get
			{
				return this._GIA_SAN;
			}
			set
			{
				if ((this._GIA_SAN != value))
				{
					this.OnGIA_SANChanging(value);
					this.SendPropertyChanging();
					this._GIA_SAN = value;
					this.SendPropertyChanged("GIA_SAN");
					this.OnGIA_SANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_LAP_PHIEU", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_LAP_PHIEU
		{
			get
			{
				return this._NGAY_LAP_PHIEU;
			}
			set
			{
				if ((this._NGAY_LAP_PHIEU != value))
				{
					this.OnNGAY_LAP_PHIEUChanging(value);
					this.SendPropertyChanging();
					this._NGAY_LAP_PHIEU = value;
					this.SendPropertyChanged("NGAY_LAP_PHIEU");
					this.OnNGAY_LAP_PHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH_TRANG_DON", DbType="Bit")]
		public System.Nullable<bool> TINH_TRANG_DON
		{
			get
			{
				return this._TINH_TRANG_DON;
			}
			set
			{
				if ((this._TINH_TRANG_DON != value))
				{
					this.OnTINH_TRANG_DONChanging(value);
					this.SendPropertyChanging();
					this._TINH_TRANG_DON = value;
					this.SendPropertyChanged("TINH_TRANG_DON");
					this.OnTINH_TRANG_DONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIO_KET_THUC_TEXT", DbType="NVarChar(10)")]
		public string GIO_KET_THUC_TEXT
		{
			get
			{
				return this._GIO_KET_THUC_TEXT;
			}
			set
			{
				if ((this._GIO_KET_THUC_TEXT != value))
				{
					this.OnGIO_KET_THUC_TEXTChanging(value);
					this.SendPropertyChanging();
					this._GIO_KET_THUC_TEXT = value;
					this.SendPropertyChanged("GIO_KET_THUC_TEXT");
					this.OnGIO_KET_THUC_TEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANG_THAI_XOA", DbType="Bit")]
		public System.Nullable<bool> TRANG_THAI_XOA
		{
			get
			{
				return this._TRANG_THAI_XOA;
			}
			set
			{
				if ((this._TRANG_THAI_XOA != value))
				{
					this.OnTRANG_THAI_XOAChanging(value);
					this.SendPropertyChanging();
					this._TRANG_THAI_XOA = value;
					this.SendPropertyChanged("TRANG_THAI_XOA");
					this.OnTRANG_THAI_XOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_START", DbType="Int")]
		public System.Nullable<int> TIME_START
		{
			get
			{
				return this._TIME_START;
			}
			set
			{
				if ((this._TIME_START != value))
				{
					this.OnTIME_STARTChanging(value);
					this.SendPropertyChanging();
					this._TIME_START = value;
					this.SendPropertyChanged("TIME_START");
					this.OnTIME_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_END", DbType="Int")]
		public System.Nullable<int> TIME_END
		{
			get
			{
				return this._TIME_END;
			}
			set
			{
				if ((this._TIME_END != value))
				{
					this.OnTIME_ENDChanging(value);
					this.SendPropertyChanging();
					this._TIME_END = value;
					this.SendPropertyChanged("TIME_END");
					this.OnTIME_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DON_DAT_SAN_CT_DAT_SAN", Storage="_CT_DAT_SANs", ThisKey="MA_DS", OtherKey="MA_DS")]
		public EntitySet<CT_DAT_SAN> CT_DAT_SANs
		{
			get
			{
				return this._CT_DAT_SANs;
			}
			set
			{
				this._CT_DAT_SANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DON_DAT_SAN", Storage="_KHACH_HANG", ThisKey="MA_KH", OtherKey="MA_KH", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.DON_DAT_SANs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.DON_DAT_SANs.Add(this);
						this._MA_KH = value.MA_KH;
					}
					else
					{
						this._MA_KH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_DON_DAT_SAN", Storage="_SAN", ThisKey="MA_SAN", OtherKey="MA_SAN", IsForeignKey=true)]
		public SAN SAN
		{
			get
			{
				return this._SAN.Entity;
			}
			set
			{
				SAN previousValue = this._SAN.Entity;
				if (((previousValue != value) 
							|| (this._SAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN.Entity = null;
						previousValue.DON_DAT_SANs.Remove(this);
					}
					this._SAN.Entity = value;
					if ((value != null))
					{
						value.DON_DAT_SANs.Add(this);
						this._MA_SAN = value.MA_SAN;
					}
					else
					{
						this._MA_SAN = default(int);
					}
					this.SendPropertyChanged("SAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DAT_SANs(CT_DAT_SAN entity)
		{
			this.SendPropertyChanging();
			entity.DON_DAT_SAN = this;
		}
		
		private void detach_CT_DAT_SANs(CT_DAT_SAN entity)
		{
			this.SendPropertyChanging();
			entity.DON_DAT_SAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH_HANG")]
	public partial class KHACH_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_KH;
		
		private string _TEN_KH;
		
		private string _SDT;
		
		private string _TEN_DN;
		
		private string _MAT_KHAU;
		
		private string _EMAIL;
		
		private string _AVATAR;
		
		private System.Nullable<bool> _TINH_TRANG_XOA;
		
		private EntitySet<DON_DAT_SAN> _DON_DAT_SANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_KHChanging(int value);
    partial void OnMA_KHChanged();
    partial void OnTEN_KHChanging(string value);
    partial void OnTEN_KHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTEN_DNChanging(string value);
    partial void OnTEN_DNChanged();
    partial void OnMAT_KHAUChanging(string value);
    partial void OnMAT_KHAUChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnAVATARChanging(string value);
    partial void OnAVATARChanged();
    partial void OnTINH_TRANG_XOAChanging(System.Nullable<bool> value);
    partial void OnTINH_TRANG_XOAChanged();
    #endregion
		
		public KHACH_HANG()
		{
			this._DON_DAT_SANs = new EntitySet<DON_DAT_SAN>(new Action<DON_DAT_SAN>(this.attach_DON_DAT_SANs), new Action<DON_DAT_SAN>(this.detach_DON_DAT_SANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_KH", DbType="NVarChar(30)")]
		public string TEN_KH
		{
			get
			{
				return this._TEN_KH;
			}
			set
			{
				if ((this._TEN_KH != value))
				{
					this.OnTEN_KHChanging(value);
					this.SendPropertyChanging();
					this._TEN_KH = value;
					this.SendPropertyChanged("TEN_KH");
					this.OnTEN_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DN", DbType="NVarChar(30)")]
		public string TEN_DN
		{
			get
			{
				return this._TEN_DN;
			}
			set
			{
				if ((this._TEN_DN != value))
				{
					this.OnTEN_DNChanging(value);
					this.SendPropertyChanging();
					this._TEN_DN = value;
					this.SendPropertyChanged("TEN_DN");
					this.OnTEN_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT_KHAU", DbType="NVarChar(50)")]
		public string MAT_KHAU
		{
			get
			{
				return this._MAT_KHAU;
			}
			set
			{
				if ((this._MAT_KHAU != value))
				{
					this.OnMAT_KHAUChanging(value);
					this.SendPropertyChanging();
					this._MAT_KHAU = value;
					this.SendPropertyChanged("MAT_KHAU");
					this.OnMAT_KHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(40)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="NVarChar(20)")]
		public string AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this.OnAVATARChanging(value);
					this.SendPropertyChanging();
					this._AVATAR = value;
					this.SendPropertyChanged("AVATAR");
					this.OnAVATARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH_TRANG_XOA", DbType="Bit")]
		public System.Nullable<bool> TINH_TRANG_XOA
		{
			get
			{
				return this._TINH_TRANG_XOA;
			}
			set
			{
				if ((this._TINH_TRANG_XOA != value))
				{
					this.OnTINH_TRANG_XOAChanging(value);
					this.SendPropertyChanging();
					this._TINH_TRANG_XOA = value;
					this.SendPropertyChanged("TINH_TRANG_XOA");
					this.OnTINH_TRANG_XOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DON_DAT_SAN", Storage="_DON_DAT_SANs", ThisKey="MA_KH", OtherKey="MA_KH")]
		public EntitySet<DON_DAT_SAN> DON_DAT_SANs
		{
			get
			{
				return this._DON_DAT_SANs;
			}
			set
			{
				this._DON_DAT_SANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DON_DAT_SANs(DON_DAT_SAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_DON_DAT_SANs(DON_DAT_SAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_SAN")]
	public partial class LOAI_SAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_LOAI;
		
		private string _TEN_LOAI;
		
		private System.Nullable<decimal> _GIA_LOAI;
		
		private EntitySet<SAN> _SANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_LOAIChanging(int value);
    partial void OnMA_LOAIChanged();
    partial void OnTEN_LOAIChanging(string value);
    partial void OnTEN_LOAIChanged();
    partial void OnGIA_LOAIChanging(System.Nullable<decimal> value);
    partial void OnGIA_LOAIChanged();
    #endregion
		
		public LOAI_SAN()
		{
			this._SANs = new EntitySet<SAN>(new Action<SAN>(this.attach_SANs), new Action<SAN>(this.detach_SANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_LOAI
		{
			get
			{
				return this._MA_LOAI;
			}
			set
			{
				if ((this._MA_LOAI != value))
				{
					this.OnMA_LOAIChanging(value);
					this.SendPropertyChanging();
					this._MA_LOAI = value;
					this.SendPropertyChanged("MA_LOAI");
					this.OnMA_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI", DbType="NVarChar(10)")]
		public string TEN_LOAI
		{
			get
			{
				return this._TEN_LOAI;
			}
			set
			{
				if ((this._TEN_LOAI != value))
				{
					this.OnTEN_LOAIChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAI = value;
					this.SendPropertyChanged("TEN_LOAI");
					this.OnTEN_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_LOAI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIA_LOAI
		{
			get
			{
				return this._GIA_LOAI;
			}
			set
			{
				if ((this._GIA_LOAI != value))
				{
					this.OnGIA_LOAIChanging(value);
					this.SendPropertyChanging();
					this._GIA_LOAI = value;
					this.SendPropertyChanged("GIA_LOAI");
					this.OnGIA_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_SAN_SAN", Storage="_SANs", ThisKey="MA_LOAI", OtherKey="MA_LOAI")]
		public EntitySet<SAN> SANs
		{
			get
			{
				return this._SANs;
			}
			set
			{
				this._SANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SANs(SAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_SAN = this;
		}
		
		private void detach_SANs(SAN entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_SAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAN")]
	public partial class SAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_SAN;
		
		private System.Nullable<int> _MA_LOAI;
		
		private System.Nullable<decimal> _GIA_SAN;
		
		private string _TEN_SAN;
		
		private System.Nullable<bool> _TINH_TRANG_XOA;
		
		private EntitySet<CT_DAT_SAN> _CT_DAT_SANs;
		
		private EntitySet<DON_DAT_SAN> _DON_DAT_SANs;
		
		private EntityRef<LOAI_SAN> _LOAI_SAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_SANChanging(int value);
    partial void OnMA_SANChanged();
    partial void OnMA_LOAIChanging(System.Nullable<int> value);
    partial void OnMA_LOAIChanged();
    partial void OnGIA_SANChanging(System.Nullable<decimal> value);
    partial void OnGIA_SANChanged();
    partial void OnTEN_SANChanging(string value);
    partial void OnTEN_SANChanged();
    partial void OnTINH_TRANG_XOAChanging(System.Nullable<bool> value);
    partial void OnTINH_TRANG_XOAChanged();
    #endregion
		
		public SAN()
		{
			this._CT_DAT_SANs = new EntitySet<CT_DAT_SAN>(new Action<CT_DAT_SAN>(this.attach_CT_DAT_SANs), new Action<CT_DAT_SAN>(this.detach_CT_DAT_SANs));
			this._DON_DAT_SANs = new EntitySet<DON_DAT_SAN>(new Action<DON_DAT_SAN>(this.attach_DON_DAT_SANs), new Action<DON_DAT_SAN>(this.detach_DON_DAT_SANs));
			this._LOAI_SAN = default(EntityRef<LOAI_SAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_SAN
		{
			get
			{
				return this._MA_SAN;
			}
			set
			{
				if ((this._MA_SAN != value))
				{
					this.OnMA_SANChanging(value);
					this.SendPropertyChanging();
					this._MA_SAN = value;
					this.SendPropertyChanged("MA_SAN");
					this.OnMA_SANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LOAI", DbType="Int")]
		public System.Nullable<int> MA_LOAI
		{
			get
			{
				return this._MA_LOAI;
			}
			set
			{
				if ((this._MA_LOAI != value))
				{
					if (this._LOAI_SAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LOAIChanging(value);
					this.SendPropertyChanging();
					this._MA_LOAI = value;
					this.SendPropertyChanged("MA_LOAI");
					this.OnMA_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_SAN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIA_SAN
		{
			get
			{
				return this._GIA_SAN;
			}
			set
			{
				if ((this._GIA_SAN != value))
				{
					this.OnGIA_SANChanging(value);
					this.SendPropertyChanging();
					this._GIA_SAN = value;
					this.SendPropertyChanged("GIA_SAN");
					this.OnGIA_SANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_SAN", DbType="NVarChar(20)")]
		public string TEN_SAN
		{
			get
			{
				return this._TEN_SAN;
			}
			set
			{
				if ((this._TEN_SAN != value))
				{
					this.OnTEN_SANChanging(value);
					this.SendPropertyChanging();
					this._TEN_SAN = value;
					this.SendPropertyChanged("TEN_SAN");
					this.OnTEN_SANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH_TRANG_XOA", DbType="Bit")]
		public System.Nullable<bool> TINH_TRANG_XOA
		{
			get
			{
				return this._TINH_TRANG_XOA;
			}
			set
			{
				if ((this._TINH_TRANG_XOA != value))
				{
					this.OnTINH_TRANG_XOAChanging(value);
					this.SendPropertyChanging();
					this._TINH_TRANG_XOA = value;
					this.SendPropertyChanged("TINH_TRANG_XOA");
					this.OnTINH_TRANG_XOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_CT_DAT_SAN", Storage="_CT_DAT_SANs", ThisKey="MA_SAN", OtherKey="MA_SAN")]
		public EntitySet<CT_DAT_SAN> CT_DAT_SANs
		{
			get
			{
				return this._CT_DAT_SANs;
			}
			set
			{
				this._CT_DAT_SANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_DON_DAT_SAN", Storage="_DON_DAT_SANs", ThisKey="MA_SAN", OtherKey="MA_SAN")]
		public EntitySet<DON_DAT_SAN> DON_DAT_SANs
		{
			get
			{
				return this._DON_DAT_SANs;
			}
			set
			{
				this._DON_DAT_SANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_SAN_SAN", Storage="_LOAI_SAN", ThisKey="MA_LOAI", OtherKey="MA_LOAI", IsForeignKey=true)]
		public LOAI_SAN LOAI_SAN
		{
			get
			{
				return this._LOAI_SAN.Entity;
			}
			set
			{
				LOAI_SAN previousValue = this._LOAI_SAN.Entity;
				if (((previousValue != value) 
							|| (this._LOAI_SAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI_SAN.Entity = null;
						previousValue.SANs.Remove(this);
					}
					this._LOAI_SAN.Entity = value;
					if ((value != null))
					{
						value.SANs.Add(this);
						this._MA_LOAI = value.MA_LOAI;
					}
					else
					{
						this._MA_LOAI = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAI_SAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DAT_SANs(CT_DAT_SAN entity)
		{
			this.SendPropertyChanging();
			entity.SAN = this;
		}
		
		private void detach_CT_DAT_SANs(CT_DAT_SAN entity)
		{
			this.SendPropertyChanging();
			entity.SAN = null;
		}
		
		private void attach_DON_DAT_SANs(DON_DAT_SAN entity)
		{
			this.SendPropertyChanging();
			entity.SAN = this;
		}
		
		private void detach_DON_DAT_SANs(DON_DAT_SAN entity)
		{
			this.SendPropertyChanging();
			entity.SAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SO_GIO")]
	public partial class SO_GIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_SO_GIO;
		
		private string _SO_GIO1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_SO_GIOChanging(int value);
    partial void OnMA_SO_GIOChanged();
    partial void OnSO_GIO1Changing(string value);
    partial void OnSO_GIO1Changed();
    #endregion
		
		public SO_GIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SO_GIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_SO_GIO
		{
			get
			{
				return this._MA_SO_GIO;
			}
			set
			{
				if ((this._MA_SO_GIO != value))
				{
					this.OnMA_SO_GIOChanging(value);
					this.SendPropertyChanging();
					this._MA_SO_GIO = value;
					this.SendPropertyChanged("MA_SO_GIO");
					this.OnMA_SO_GIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_GIO1", DbType="NChar(10)")]
		public string SO_GIO1
		{
			get
			{
				return this._SO_GIO1;
			}
			set
			{
				if ((this._SO_GIO1 != value))
				{
					this.OnSO_GIO1Changing(value);
					this.SendPropertyChanging();
					this._SO_GIO1 = value;
					this.SendPropertyChanged("SO_GIO1");
					this.OnSO_GIO1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONG_KE")]
	public partial class THONG_KE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private int _MA_SAN;
		
		private System.Nullable<System.DateTime> _NGAY_DAT;
		
		private System.Nullable<System.DateTime> _NGAY_BAT_DAU;
		
		private System.Nullable<System.DateTime> _NGAY_KET_THUC;
		
		private System.Nullable<decimal> _TONG_TIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMA_SANChanging(int value);
    partial void OnMA_SANChanged();
    partial void OnNGAY_DATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_DATChanged();
    partial void OnNGAY_BAT_DAUChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_BAT_DAUChanged();
    partial void OnNGAY_KET_THUCChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_KET_THUCChanged();
    partial void OnTONG_TIENChanging(System.Nullable<decimal> value);
    partial void OnTONG_TIENChanged();
    #endregion
		
		public THONG_KE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SAN", DbType="Int NOT NULL")]
		public int MA_SAN
		{
			get
			{
				return this._MA_SAN;
			}
			set
			{
				if ((this._MA_SAN != value))
				{
					this.OnMA_SANChanging(value);
					this.SendPropertyChanging();
					this._MA_SAN = value;
					this.SendPropertyChanged("MA_SAN");
					this.OnMA_SANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_DAT
		{
			get
			{
				return this._NGAY_DAT;
			}
			set
			{
				if ((this._NGAY_DAT != value))
				{
					this.OnNGAY_DATChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DAT = value;
					this.SendPropertyChanged("NGAY_DAT");
					this.OnNGAY_DATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_BAT_DAU", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_BAT_DAU
		{
			get
			{
				return this._NGAY_BAT_DAU;
			}
			set
			{
				if ((this._NGAY_BAT_DAU != value))
				{
					this.OnNGAY_BAT_DAUChanging(value);
					this.SendPropertyChanging();
					this._NGAY_BAT_DAU = value;
					this.SendPropertyChanged("NGAY_BAT_DAU");
					this.OnNGAY_BAT_DAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_KET_THUC", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_KET_THUC
		{
			get
			{
				return this._NGAY_KET_THUC;
			}
			set
			{
				if ((this._NGAY_KET_THUC != value))
				{
					this.OnNGAY_KET_THUCChanging(value);
					this.SendPropertyChanging();
					this._NGAY_KET_THUC = value;
					this.SendPropertyChanged("NGAY_KET_THUC");
					this.OnNGAY_KET_THUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONG_TIEN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TONG_TIEN
		{
			get
			{
				return this._TONG_TIEN;
			}
			set
			{
				if ((this._TONG_TIEN != value))
				{
					this.OnTONG_TIENChanging(value);
					this.SendPropertyChanging();
					this._TONG_TIEN = value;
					this.SendPropertyChanged("TONG_TIEN");
					this.OnTONG_TIENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SO_PHUT")]
	public partial class SO_PHUT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_SO_PHUT;
		
		private string _SO_PHUT1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_SO_PHUTChanging(int value);
    partial void OnMA_SO_PHUTChanged();
    partial void OnSO_PHUT1Changing(string value);
    partial void OnSO_PHUT1Changed();
    #endregion
		
		public SO_PHUT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SO_PHUT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_SO_PHUT
		{
			get
			{
				return this._MA_SO_PHUT;
			}
			set
			{
				if ((this._MA_SO_PHUT != value))
				{
					this.OnMA_SO_PHUTChanging(value);
					this.SendPropertyChanging();
					this._MA_SO_PHUT = value;
					this.SendPropertyChanged("MA_SO_PHUT");
					this.OnMA_SO_PHUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_PHUT1", DbType="NChar(10)")]
		public string SO_PHUT1
		{
			get
			{
				return this._SO_PHUT1;
			}
			set
			{
				if ((this._SO_PHUT1 != value))
				{
					this.OnSO_PHUT1Changing(value);
					this.SendPropertyChanging();
					this._SO_PHUT1 = value;
					this.SendPropertyChanged("SO_PHUT1");
					this.OnSO_PHUT1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
